### ISSUE TITLE
Use generics

### ISSUE THREAD

**Issue by lil5** [realTristan/GoQueue#1]
Instead of using `type Item = interface{}` how is the idea of moving to using generics first introduced in go1.18?

Would you be interested in a PR adopting this suggestion?

P.S. found your project thanks to GoLang Weekly (@xojoc) on the fediverse https://mastodon.social/@golang_discussions/108795842782302939

**Comment by realTristan** [comment]
I will be adding a separate folder for generics for anyone using above 1.18. Thank you for the pull request! I appreciate it a lot.
